classdef ModelBuilder
    methods (Static)
        function M = minimal(nNodes, nkd)
            if nargin<1, nNodes = 2; end
            if nargin<2, nkd    = 3; end
            K = repmat(struct('x',0,'y',0), 1, nNodes);
            for i = 1:nNodes, K(i).x = i-1; K(i).y = 0; end

            M = struct( ...
              'Knoten',        K, ...
              'Stab',          struct([]), ...
              'Feder',         struct([]), ...
              'KnotenLast',    struct([]), ...
              'StabLast',      struct([]), ...
              'SPC',           struct([]), ...
              'Info',          struct('nKnoten',nNodes,'nKnotenDOF',nkd,'nStaebe',0,'nFedern',0,'nSPC',0,'nTeilsys',0), ...
              'gew_output',    1, ...
              'Einflusslinie', false );
        end

        function S = oneBarHoriz(M, sNode, eNode, E, A, I)
            if nargin<2, sNode=1; end
            if nargin<3, eNode=2; end
            if nargin<4, E = tests.util.Const.E; end
            if nargin<5, A = tests.util.Const.A; end
            if nargin<6, I = tests.util.Const.I; end

            S = struct('sNode',sNode,'eNode',eNode, ...
                       'sRelease',[],'eRelease',[], ...
                       'E',E,'A',A,'Iy',I, ...
                       'cs',1,'sn',0);  % horizontal
        end
    end
end
